### ISSUE TITLE
处理相当路径有问题

### ISSUE THREAD

**Issue by xiabingwu** [chyingp/grunt-inline#33]
1.比如如果使用
           dist: {
                src: ['../publish/index.html'],
                dest: ['../publish_min/']
            }
处理后的结果只会覆盖源文件 不会copy到目标目录中的

**Comment by Lynn-cc** [comment]
我也有这个问题，并且支持的files格式只有数组这一种。。而且也不能支持父目录匹配。。

**Comment by xiabingwu** [comment]
哈哈 都是tx的

**Comment by Lynn-cc** [comment]
楼上也是呀！已经rtx联系作者了~~嘿嘿嘿~~~ps、再来点人拉个grunt-inline的rtx群好了~~ :D

**Comment by xiabingwu** [comment]
有道理~

**Comment by chyingp** [comment]
@Lynn-cc @xiabingwu 

已经fix。升级到版本`0.3.3`试试 :)

**Comment by xiabingwu** [comment]
赞
