### ISSUE TITLE
Support file globbing for input and output

### ISSUE THREAD

**Issue by SonniesEdge** [chyingp/grunt-inline#35]
In the example below, if multiple files and folders are specified via file globbing, the destination value is ignored. 

**Grunt code:**
```
    inline: {
      dist: {
          files: [{
            expand: true,
            cwd:  'source/',
            src: ['**/*.html'],
            dest: 'destination/'
          }]
      }
    }
```

**Output:** (grunt inline:dist --verbose)
```
OK
Reading source/index.html...OK
Processing source/index.html...Writing source/index.html...OK
OK
Reading source/test/index.html...OK
Processing source/test/index.html...Writing source/test/index.html...OK
OK
```

**Comment by Lynn-cc** [comment]
I have the same problem...

**Comment by chyingp** [comment]
@SonniesEdge @Lynn-cc 

I will take care of your problem as soon as possible :)

**Comment by chyingp** [comment]
@SonniesEdge @Lynn-cc 

I've get the bug fixed. Try version `0.3.3` and check whether the problem is fixed.
